# Generated by Django 4.1.6 on 2023-03-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateField(default=83.29166666666667),
            preserve_default=False,
        ),
    ]
